image: gradle:4.6-jdk8-alpine 

variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
  GIT_STRATEGY: clone

before_script: 
  - echo "Let's run." 

stages:
  - build
  # - test

Build:
  stage: build 
  script: 
    # - ./A2/gradlew build -x test
     - ./A3/gradlew build
  tags:
    - grad

# Test: 
#   stage: test 
#   script:
#     # - ./A2/gradlew test
#        - ./A3/gradlew test
  # tags:
  #   - grad
  # artifacts:
  #   when: always
  #   reports:
  #     # junit: ./A2/app/build/test-results/test/TEST-*.xml
  #     junit: ./A3/build/test-results/test/TEST-*.xml

after_script: 
  - echo "Finish"

